server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:63342"  # Add your specific origin
              - "http://localhost:*"
              - "http://127.0.0.1:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600


      routes:
        - id: auth-public-endpoints
          uri: lb://user-service
          predicates:
            - Path=/api/auth/register, /api/auth/login
          # No AuthenticationFilter here

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/current-user, /api/users/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 10
                redis-rate-limiter.burst-capacity: 20
                redis-rate-limiter.requested-tokens: 1

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profiles/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: profile-service
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 10
                redis-rate-limiter.burst-capacity: 20

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: postCircuitBreaker
                fallbackUri: forward:/fallback

  data:
    redis:
      host: localhost
      password: 123456
      port: 6379
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      profile-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      post-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  data:
    redis:
      password: 123456
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security.web: DEBUG
    org.springframework.cloud.gateway: DEBUG



