server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5500"
              - "http://127.0.0.1:5500"
              - "http://localhost:63342"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: auth-public-endpoints
          uri: lb://user-service
          predicates:
            - Path=/api/auth/register, /api/auth/login, /api/auth/current-user
          # No AuthenticationFilter here

        - id: token-validation
          uri: lb://user-service
          predicates:
            - Path=/api/users/validateToken
          # No AuthenticationFilter here

        - id: users-public
          uri: lb://user-service
          predicates:
            - Path=/api/users
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback

        - id: users-random-public
          uri: lb://user-service
          predicates:
            - Path=/api/users/random, /api/users/random/exclude
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback


        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profiles/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: profile-service
                fallbackUri: forward:/fallback


        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: postCircuitBreaker
                fallbackUri: forward:/fallback

        - id: followers-service
          uri: lb://followers-service
          predicates:
            - Path=/api/follows/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: followers-service
                fallbackUri: forward:/fallback

        - id: messaging-service
          uri: lb://messaging-service
          predicates:
            - Path=/api/messages/**
          filters:
            - AuthenticationFilter


        - id: file-upload-service
          uri: lb://FILE-UPLOAD-SERVICE
          predicates:
            - Path=/api/upload/**
          filters:
            - name: CircuitBreaker
              args:
                name: file-upload-service
                fallbackUri: forward:/fallback

  data:
    redis:
      host: localhost
      password: 123456
      port: 6379
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      profile-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      post-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      followers-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      messaging-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      file-upload-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s


jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  data:
    redis:
      password: 123456
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security.web: DEBUG
    org.springframework.cloud.gateway: DEBUG



