spring:
  application:
    name: file-upload-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

cloudinary:
  cloud_name: xxx
  api_key: xxx
  api_secret: xxx

server:
  port: 9895

