spring:
  application:
    name: file-upload-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

cloudinary:
  cloud_name: dzqln71bi
  api_key: 597924396389619
  api_secret: jGiGrBYYjALKc0wQu-t1pFmH2c4

server:
  port: 9895

