server:
  port: 8084

spring:
  application:
    name: followers-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: followers_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG